/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import progra3so.FileSytem.DiskManager;
import progra3so.FileSytem.FileManager;
import progra3so.FileSytem.Node;
import progra3so.Progra3SO;

/**
 *
 * @author Fabian
 */
public class principal extends javax.swing.JFrame {
    
    FileManager FM = new FileManager();
    DiskManager diskManager = new DiskManager();
        
    /**
     * Creates new form principal
     * @throws java.lang.Exception
     */
    public principal() throws Exception {
        initComponents();
        Oculta();
        //Aqui se crea el disco
        String[] split = "/".split("/");
        String url = "C:\\Users\\Fabian\\Desktop\\disco.txt";
        try {
            FM.Create(url, 32, 10);
            //diskManager.WriteFile("Hola");
            //List<Integer> WriteFile = diskManager.WriteFile("Esta es una prueba de mas de 32 bits de largo");
            //diskManager.WriteFile("Adieu");
            //diskManager.DeleteFile(WriteFile);
            //diskManager.WriteFile("En un hermoso dia de verano los pajaros cantan, rien y sonrien a la luz de sol");
            
            FM.MkDir("Documentos");
            FM.MkDir("Musica");
            FM.MkDir("Imagenes");
            FM.MkDir("Videos");
                FM.CambiarDir("./Documentos");
                    FM.MkDir("FolderDocumentos");
                    FM.File("info1", ".txt", "Fabian Lopez Quesada");
                    FM.File("info2", ".txt", "Jose Pablo Parajeles");
                    FM.File("info3", ".txt", "Rudiney Mejias Calvo");
                    FM.File("info4", ".txt", "Kenneth Meza Chaves");
                        FM.CambiarDir("./FolderDocumentos");
                        FM.File("info5", ".txt", "Maria Fernanda Chaves");
                    FM.CambiarDir("../");
                    FM.CambiarDir("../");
                FM.CambiarDir("Musica");
                    FM.MkDir("Rock");
                    FM.MkDir("Metal");
                FM.CambiarDir("../");
                FM.CambiarDir("./Imagenes");
                    FM.MkDir("Fiesta");
                    FM.File("Foto1", ".jpg", "Descripcion de la foto");
                    FM.CambiarDir("./Fiesta");
                        FM.File("Foto2", ".jpg", "Descripcion de la foto");
                        FM.File("Foto3", ".jpg", "Descripcion de la foto");
                    FM.CambiarDir("../");
                    FM.CambiarDir("../");
                FM.File("FS", ".doc", "Descripcion del file system");
                
            List<Node> ListaFolders = new ArrayList<Node>();
            DefaultListModel listModel = new DefaultListModel();
            ListaFolders = FM.ListarDir();
            listModel.add(0, "..");
            for (int i = 1; i < ListaFolders.size()+1; i++) {
                //System.out.println(ListaFolders.get(i).FullName());
                listModel.add(i, ListaFolders.get(i-1).FullName());
            }
            //Asociar el modelo de lista al JList
            jList1.setModel(listModel);
        
        
        } catch (IOException ex) {
            Logger.getLogger(Progra3SO.class.getName()).log(Level.SEVERE, null, ex);
        }
        //-------------------------------------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpcionesFS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jPanelCrearDirectorio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextNombreDirectorio = new javax.swing.JTextField();
        jButtonNombreDirectorio = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelCrearArchivo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextNombreArchivo = new javax.swing.JTextField();
        jButtonNombreArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextExtensionArchivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextContenidoArchivo = new javax.swing.JTextField();
        jPanelVerPropiedades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonVerPropiedades = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelCreacion = new javax.swing.JLabel();
        jLabelTamanio = new javax.swing.JLabel();
        jLabelUltimaModificacion = new javax.swing.JLabel();
        jPanelContFile = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFile = new javax.swing.JLabel();
        jButtonContFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaContFile = new javax.swing.JTextArea();
        jPanelModFile = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("File System");
        setMaximumSize(new java.awt.Dimension(600, 600));
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        jTextField1.setForeground(new java.awt.Color(0, 153, 153));
        jTextField1.setText("/");

        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("<-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(0, 153, 153));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(0, 102, 102));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addGap(5, 5, 5))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 328));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(0, 102, 102));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton1.setText("Crear Directorio");
        jRadioButton1.setToolTipText("");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton2.setText("Crear Archivo");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton2MouseClicked(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton3.setText("Ver Propiedades");
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton3MouseClicked(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton4.setText("ModFile");
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton4MouseClicked(evt);
            }
        });

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton5.setText("ContFile");
        jRadioButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton5MouseClicked(evt);
            }
        });
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton6.setText("Copy");

        jRadioButton7.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton7.setText("Mover");

        jRadioButton8.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton8.setText("Remove");

        jRadioButton9.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton9.setText("Find");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.setBackground(new java.awt.Color(255, 255, 255));
        OpcionesFS.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(0, 102, 102));
        jRadioButton10.setText("Tree");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton3)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton4)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton5)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton6)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton7)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton8)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton9)
                .addGap(15, 15, 15)
                .addComponent(jRadioButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCrearDirectorio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCrearDirectorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nombre del directorio");

        jTextNombreDirectorio.setForeground(new java.awt.Color(0, 102, 102));

        jButtonNombreDirectorio.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButtonNombreDirectorio.setForeground(new java.awt.Color(0, 102, 102));
        jButtonNombreDirectorio.setText("Agregar");
        jButtonNombreDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombreDirectorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCrearDirectorioLayout = new javax.swing.GroupLayout(jPanelCrearDirectorio);
        jPanelCrearDirectorio.setLayout(jPanelCrearDirectorioLayout);
        jPanelCrearDirectorioLayout.setHorizontalGroup(
            jPanelCrearDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearDirectorioLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearDirectorioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonNombreDirectorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNombreDirectorio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelCrearDirectorioLayout.setVerticalGroup(
            jPanelCrearDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearDirectorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearDirectorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCrearDirectorioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextNombreDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonNombreDirectorio)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelCrearArchivo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCrearArchivo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Nombre del archivo");

        jTextNombreArchivo.setForeground(new java.awt.Color(0, 102, 102));

        jButtonNombreArchivo.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButtonNombreArchivo.setForeground(new java.awt.Color(0, 102, 102));
        jButtonNombreArchivo.setText("Agregar");
        jButtonNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombreArchivoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Extensión");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Contenido:");

        javax.swing.GroupLayout jPanelCrearArchivoLayout = new javax.swing.GroupLayout(jPanelCrearArchivo);
        jPanelCrearArchivo.setLayout(jPanelCrearArchivoLayout);
        jPanelCrearArchivoLayout.setHorizontalGroup(
            jPanelCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNombreArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCrearArchivoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(111, 111, 111))
                    .addGroup(jPanelCrearArchivoLayout.createSequentialGroup()
                        .addComponent(jTextNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextExtensionArchivo))
                    .addGroup(jPanelCrearArchivoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextContenidoArchivo))
                .addContainerGap())
        );
        jPanelCrearArchivoLayout.setVerticalGroup(
            jPanelCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCrearArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextExtensionArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextContenidoArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNombreArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVerPropiedades.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVerPropiedades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Archivo/Directorio:");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("..");

        jButtonVerPropiedades.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButtonVerPropiedades.setForeground(new java.awt.Color(0, 102, 102));
        jButtonVerPropiedades.setText("Ver propiedades");
        jButtonVerPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPropiedadesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Fecha de creación:");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Tamaño:");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Última modificación:");

        jLabelCreacion.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabelCreacion.setForeground(new java.awt.Color(0, 102, 102));
        jLabelCreacion.setText("...");

        jLabelTamanio.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabelTamanio.setForeground(new java.awt.Color(0, 102, 102));
        jLabelTamanio.setText("...");

        jLabelUltimaModificacion.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabelUltimaModificacion.setForeground(new java.awt.Color(0, 102, 102));
        jLabelUltimaModificacion.setText("...");

        javax.swing.GroupLayout jPanelVerPropiedadesLayout = new javax.swing.GroupLayout(jPanelVerPropiedades);
        jPanelVerPropiedades.setLayout(jPanelVerPropiedadesLayout);
        jPanelVerPropiedadesLayout.setHorizontalGroup(
            jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVerPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVerPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVerPropiedadesLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUltimaModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelVerPropiedadesLayout.createSequentialGroup()
                        .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCreacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelVerPropiedadesLayout.setVerticalGroup(
            jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPropiedadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelCreacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelTamanio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVerPropiedadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelUltimaModificacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContFile.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Archivo");

        jLabelFile.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabelFile.setForeground(new java.awt.Color(0, 102, 102));
        jLabelFile.setText("..");

        jButtonContFile.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jButtonContFile.setForeground(new java.awt.Color(0, 102, 102));
        jButtonContFile.setText("Ver contenido");
        jButtonContFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContFileActionPerformed(evt);
            }
        });

        jTextAreaContFile.setColumns(20);
        jTextAreaContFile.setRows(5);
        jScrollPane2.setViewportView(jTextAreaContFile);

        javax.swing.GroupLayout jPanelContFileLayout = new javax.swing.GroupLayout(jPanelContFile);
        jPanelContFile.setLayout(jPanelContFileLayout);
        jPanelContFileLayout.setHorizontalGroup(
            jPanelContFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonContFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContFileLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanelContFileLayout.setVerticalGroup(
            jPanelContFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelModFile.setBackground(new java.awt.Color(255, 255, 255));
        jPanelModFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelModFileLayout = new javax.swing.GroupLayout(jPanelModFile);
        jPanelModFile.setLayout(jPanelModFileLayout);
        jPanelModFileLayout.setHorizontalGroup(
            jPanelModFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelModFileLayout.setVerticalGroup(
            jPanelModFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCrearDirectorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelCrearArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVerPropiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelModFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanelCrearDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCrearArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVerPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelContFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelModFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCrearDirectorio.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        jLabel2.setText(jList1.getSelectedValue().toString());
        jLabelFile.setText(jList1.getSelectedValue().toString());
        JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) 
        {
        
         try {
            if (jList1.getSelectedValue().toString()==".."){
                FM.CambiarDir("../");
            }
            else{
            //Se cambia de directorio
            FM.CambiarDir("./"+jList1.getSelectedValue().toString());
            }
            System.out.println("./"+jList1.getSelectedValue().toString());
            //Se limpia la lista
            DefaultListModel listModel = (DefaultListModel) jList1.getModel();
            listModel.removeAllElements();
            //Se obtienen los directorios y archivos que tiene el directorio seleccionado
            List<Node> ListaFolders = new ArrayList<Node>();
            DefaultListModel listModelNuevo = (DefaultListModel) jList1.getModel();
            
            ListaFolders = FM.ListarDir();
            listModelNuevo.add(0, "..");
            for (int i = 1; i < ListaFolders.size()+1; i++) {
                //System.out.println(ListaFolders.get(i).FullName());
                listModelNuevo.add(i, ListaFolders.get(i-1).FullName());
            }
            //Asociar el modelo de lista al JList
            jList1.setModel(listModelNuevo);
            jTextField1.setText(FM.getCurrentFolder().FullName().toString());
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            //Se cambia de directorio
            FM.CambiarDir("../");
            //Se limpia la lista
            DefaultListModel listModel = (DefaultListModel) jList1.getModel();
            listModel.removeAllElements();
            //Se obtienen los directorios y archivos que tiene el directorio seleccionado
            List<Node> ListaFolders = new ArrayList<Node>();
            DefaultListModel listModelNuevo = (DefaultListModel) jList1.getModel();
            ListaFolders = FM.ListarDir();
            listModelNuevo.add(0, "..");
            for (int i = 1; i < ListaFolders.size()+1; i++) {
                //System.out.println(ListaFolders.get(i).FullName());
                listModelNuevo.add(i, ListaFolders.get(i-1).FullName());
            }
            //Asociar el modelo de lista al JList
            jList1.setModel(listModelNuevo);
            jTextField1.setText(FM.getCurrentFolder().FullName().toString());
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButtonNombreDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombreDirectorioActionPerformed
        // TODO add your handling code here:
        Crear(1);
    }//GEN-LAST:event_jButtonNombreDirectorioActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        Oculta();
        jPanelCrearDirectorio.setVisible(true);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void jRadioButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MouseClicked
        // TODO add your handling code here:
        Oculta();
        jPanelCrearArchivo.setVisible(true);
    }//GEN-LAST:event_jRadioButton2MouseClicked

    private void jButtonNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombreArchivoActionPerformed
        // TODO add your handling code here:
        Crear(2);
    }//GEN-LAST:event_jButtonNombreArchivoActionPerformed

    private void jButtonVerPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPropiedadesActionPerformed
        // TODO add your handling code here:
        if (jLabel2.getText()==".."){
        JOptionPane.showMessageDialog(null, "Debe seleccionar un directorio o archivo!");   
        }
        else{
        try {
            FM.SelectFile("./"+jLabel2.getText());
            jLabelCreacion.setText(FM.VerPropiedades().getCreationDate().toString());
            jLabelTamanio.setText(String.valueOf(FM.VerPropiedades().getSize()));
            jLabelUltimaModificacion.setText(FM.VerPropiedades().getLastModifiedDate().toString());            
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonVerPropiedadesActionPerformed

    private void jRadioButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MouseClicked
        // TODO add your handling code here:
        Oculta();
        jPanelVerPropiedades.setVisible(true);
    }//GEN-LAST:event_jRadioButton3MouseClicked

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButtonContFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContFileActionPerformed
        if (jLabelFile.getText()==".."){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un archivo!");   
        }
        else{
        try {
            // TODO add your handling code here:
            FM.SelectFile("./"+jLabelFile.getText());
            jTextAreaContFile.setText("");
            System.out.println(jLabelFile.getText());
            jTextAreaContFile.setText(FM.ContFile());
        } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButtonContFileActionPerformed

    private void jRadioButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton5MouseClicked
        // TODO add your handling code here:
        Oculta();
        jPanelContFile.setVisible(true);
    }//GEN-LAST:event_jRadioButton5MouseClicked

    private void jRadioButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MouseClicked
        // TODO add your handling code here:
        Oculta();
        jPanelModFile.setVisible(true);
    }//GEN-LAST:event_jRadioButton4MouseClicked

    public void Oculta(){
    jPanelCrearDirectorio.setVisible(false);
    jPanelCrearArchivo.setVisible(false);
    jPanelVerPropiedades.setVisible(false);
    jPanelContFile.setVisible(false);
    jPanelModFile.setVisible(false);
    }
    public void Crear(int valor)
    {
        try {
            if (valor==1){
            FM.MkDir(jTextNombreDirectorio.getText());
            }
            else{
            FM.File(jTextNombreArchivo.getText(), jTextExtensionArchivo.getText(),jTextContenidoArchivo.getText());                        
            }
            //Se limpia la lista
            DefaultListModel listModel = (DefaultListModel) jList1.getModel();
            listModel.removeAllElements();
            //Se obtienen los directorios y archivos que tiene el directorio seleccionado
            List<Node> ListaFolders = new ArrayList<Node>();
            DefaultListModel listModelNuevo = (DefaultListModel) jList1.getModel();
            ListaFolders = FM.ListarDir();
            listModelNuevo.add(0, "..");
            for (int i = 1; i < ListaFolders.size()+1; i++) {
                //System.out.println(ListaFolders.get(i).FullName());
                listModelNuevo.add(i, ListaFolders.get(i-1).FullName());
            }
            //Asociar el modelo de lista al JList
            jList1.setModel(listModelNuevo);
            jTextField1.setText(FM.getCurrentFolder().FullName().toString());
            if (valor==1){
            JOptionPane.showMessageDialog(null, "Directorio "+jTextNombreDirectorio.getText()+" creado correctamente!");
            jTextNombreDirectorio.setText("");
            }else{
            JOptionPane.showMessageDialog(null, "Archivo "+jTextNombreArchivo.getText()+" creado correctamente!");
            jTextNombreArchivo.setText("");
            jTextExtensionArchivo.setText("");
            jTextContenidoArchivo.setText("");
            }
         } catch (Exception ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new principal().setVisible(true);
                    
                } catch (Exception ex) {
                    Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup OpcionesFS;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonContFile;
    private javax.swing.JButton jButtonNombreArchivo;
    private javax.swing.JButton jButtonNombreDirectorio;
    private javax.swing.JButton jButtonVerPropiedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCreacion;
    private javax.swing.JLabel jLabelFile;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JLabel jLabelUltimaModificacion;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelContFile;
    private javax.swing.JPanel jPanelCrearArchivo;
    private javax.swing.JPanel jPanelCrearDirectorio;
    private javax.swing.JPanel jPanelModFile;
    private javax.swing.JPanel jPanelVerPropiedades;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaContFile;
    private javax.swing.JTextField jTextContenidoArchivo;
    private javax.swing.JTextField jTextExtensionArchivo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNombreArchivo;
    private javax.swing.JTextField jTextNombreDirectorio;
    // End of variables declaration//GEN-END:variables
}
